//! Integration tests validating Rust output against R GenomicSEM reference data.
//!
//! Fixtures are pre-generated by `tests/generate_reference.R` and committed to the repo.
//! Run with: `cargo test -p gsem --test r_validation`

use std::path::PathBuf;

use faer::Mat;
use serde_json::Value;

// ── Helpers ──────────────────────────────────────────────────────────────────

fn fixtures_dir() -> PathBuf {
    let mut p = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    p.pop(); // crates/
    p.pop(); // repo root
    p.push("tests");
    p.push("fixtures");
    p
}

fn load_fixture(name: &str) -> Value {
    let path = fixtures_dir().join(format!("{name}.json"));
    let data = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("failed to read fixture {}: {e}", path.display()));
    serde_json::from_str(&data).unwrap_or_else(|e| panic!("invalid JSON in {name}.json: {e}"))
}

fn json_to_mat(val: &Value) -> Mat<f64> {
    let rows: Vec<Vec<f64>> = val
        .as_array()
        .unwrap()
        .iter()
        .map(|row| {
            row.as_array()
                .unwrap()
                .iter()
                .map(|v| v.as_f64().unwrap())
                .collect()
        })
        .collect();
    let nrows = rows.len();
    let ncols = rows[0].len();
    Mat::from_fn(nrows, ncols, |i, j| rows[i][j])
}

fn json_to_vec(val: &Value) -> Vec<f64> {
    val.as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_f64().unwrap())
        .collect()
}

fn assert_mat_close(a: &Mat<f64>, b: &Mat<f64>, tol: f64, msg: &str) {
    assert_eq!(a.nrows(), b.nrows(), "{msg}: row count mismatch");
    assert_eq!(a.ncols(), b.ncols(), "{msg}: col count mismatch");
    for i in 0..a.nrows() {
        for j in 0..a.ncols() {
            let diff = (a[(i, j)] - b[(i, j)]).abs();
            assert!(
                diff < tol,
                "{msg}: [{i},{j}] Rust={} R={} diff={diff} (tol={tol})",
                a[(i, j)],
                b[(i, j)]
            );
        }
    }
}

fn assert_vec_close(a: &[f64], b: &[f64], tol: f64, msg: &str) {
    assert_eq!(
        a.len(),
        b.len(),
        "{msg}: length mismatch {} vs {}",
        a.len(),
        b.len()
    );
    for (i, (&av, &bv)) in a.iter().zip(b.iter()).enumerate() {
        let diff = (av - bv).abs();
        assert!(
            diff < tol,
            "{msg}: [{i}] Rust={av} R={bv} diff={diff} (tol={tol})"
        );
    }
}

// ── Test Case 1: nearPD ─────────────────────────────────────────────────────

#[test]
fn test_near_pd_matches_r() {
    let fix = load_fixture("near_pd");
    let input = json_to_mat(&fix["input"]);
    let expected = json_to_mat(&fix["expected"]);

    let result = gsem_matrix::near_pd::nearest_pd(&input, true, 100, 1e-8).unwrap();
    assert_mat_close(&result, &expected, 1e-7, "nearPD");
}

// ── Test Case 2: vech ───────────────────────────────────────────────────────

#[test]
fn test_vech_3x3_matches_r() {
    let fix = load_fixture("vech_3x3");
    let input = json_to_mat(&fix["input"]);
    let expected_vech = json_to_vec(&fix["vech"]);
    let expected_rev = json_to_mat(&fix["reverse"]);

    let v = gsem_matrix::vech::vech(&input).unwrap();
    assert_vec_close(&v, &expected_vech, 1e-15, "vech 3x3");

    let rev = gsem_matrix::vech::vech_reverse(&v, 3).unwrap();
    assert_mat_close(&rev, &expected_rev, 1e-15, "vech_reverse 3x3");
}

#[test]
fn test_vech_4x4_matches_r() {
    let fix = load_fixture("vech_4x4");
    let input = json_to_mat(&fix["input"]);
    let expected_vech = json_to_vec(&fix["vech"]);
    let expected_rev = json_to_mat(&fix["reverse"]);

    let v = gsem_matrix::vech::vech(&input).unwrap();
    assert_vec_close(&v, &expected_vech, 1e-15, "vech 4x4");

    let rev = gsem_matrix::vech::vech_reverse(&v, 4).unwrap();
    assert_mat_close(&rev, &expected_rev, 1e-15, "vech_reverse 4x4");
}

// ── Test Case 3: cov2cor ────────────────────────────────────────────────────

#[test]
fn test_cov_to_cor_matches_r() {
    let fix = load_fixture("cov_to_cor");
    let input = json_to_mat(&fix["input"]);
    let expected = json_to_mat(&fix["expected"]);

    let result = gsem_matrix::smooth::cov_to_cor(&input);
    assert_mat_close(&result, &expected, 1e-12, "cov_to_cor");
}

// ── Test Case 4: V_SNP construction ─────────────────────────────────────────

fn load_v_snp_inputs(fix: &Value) -> (Vec<f64>, Mat<f64>, f64, usize) {
    let se = json_to_vec(&fix["se_snp"]);
    let i_ld = json_to_mat(&fix["i_ld"]);
    let var_snp = fix["var_snp"].as_f64().unwrap();
    let k = fix["k"].as_u64().unwrap() as usize;
    (se, i_ld, var_snp, k)
}

#[test]
fn test_v_snp_standard_matches_r() {
    let fix = load_fixture("v_snp_standard");
    let (se, i_ld, var_snp, k) = load_v_snp_inputs(&fix);
    let expected = json_to_mat(&fix["expected"]);

    let result = gsem::gwas::gc_correction::build_v_snp(
        &se,
        &i_ld,
        var_snp,
        gsem::gwas::gc_correction::GcMode::Standard,
        k,
    );
    assert_mat_close(&result, &expected, 1e-12, "V_SNP standard");
}

#[test]
fn test_v_snp_conservative_matches_r() {
    let fix = load_fixture("v_snp_conservative");
    let (se, i_ld, var_snp, k) = load_v_snp_inputs(&fix);
    let expected = json_to_mat(&fix["expected"]);

    let result = gsem::gwas::gc_correction::build_v_snp(
        &se,
        &i_ld,
        var_snp,
        gsem::gwas::gc_correction::GcMode::Conservative,
        k,
    );
    assert_mat_close(&result, &expected, 1e-12, "V_SNP conservative");
}

#[test]
fn test_v_snp_none_matches_r() {
    let fix = load_fixture("v_snp_none");
    let (se, i_ld, var_snp, k) = load_v_snp_inputs(&fix);
    let expected = json_to_mat(&fix["expected"]);

    let result = gsem::gwas::gc_correction::build_v_snp(
        &se,
        &i_ld,
        var_snp,
        gsem::gwas::gc_correction::GcMode::None,
        k,
    );
    assert_mat_close(&result, &expected, 1e-12, "V_SNP none");
}

// ── Test Case 5: S_Full construction ────────────────────────────────────────

#[test]
fn test_s_full_matches_r() {
    let fix = load_fixture("s_full");
    let s_ld = json_to_mat(&fix["s_ld"]);
    let beta_snp = json_to_vec(&fix["beta_snp"]);
    let var_snp = fix["var_snp"].as_f64().unwrap();
    let expected = json_to_mat(&fix["expected"]);
    let k = s_ld.nrows();

    let result = gsem::gwas::add_snps::build_s_full(&s_ld, &beta_snp, var_snp, k);
    assert_mat_close(&result, &expected, 1e-12, "S_Full");
}

// ── Test Case 6: V_Full construction ────────────────────────────────────────

#[test]
fn test_v_full_matches_r() {
    let fix = load_fixture("v_full");
    let v_ld = json_to_mat(&fix["v_ld"]);
    let var_snp_se2 = fix["var_snp_se2"].as_f64().unwrap();
    let k = fix["k"].as_u64().unwrap() as usize;
    let expected = json_to_mat(&fix["expected"]);

    // We need se_snp and i_ld to reconstruct V_SNP inside build_v_full,
    // but the R fixture gives us V_SNP directly. Use the v_snp_standard inputs.
    let v_snp_fix = load_fixture("v_snp_standard");
    let se = json_to_vec(&v_snp_fix["se_snp"]);
    let i_ld = json_to_mat(&v_snp_fix["i_ld"]);
    let var_snp = v_snp_fix["var_snp"].as_f64().unwrap();

    let result = gsem::gwas::add_snps::build_v_full(
        &v_ld,
        &se,
        var_snp,
        var_snp_se2,
        &i_ld,
        gsem::gwas::gc_correction::GcMode::Standard,
        k,
    );
    assert_mat_close(&result, &expected, 1e-10, "V_Full");
}

// ── Test Case 7: Z_pre (GC-adjusted Z-scores) ──────────────────────────────

#[test]
fn test_z_pre_matches_r() {
    let fix = load_fixture("z_pre");
    let beta = json_to_vec(&fix["beta"]);
    let se = json_to_vec(&fix["se"]);
    let i_ld = json_to_mat(&fix["i_ld"]);
    let k = beta.len();

    let z_std = gsem::gwas::gc_correction::gc_adjusted_z(
        &beta,
        &se,
        &i_ld,
        gsem::gwas::gc_correction::GcMode::Standard,
        k,
    );
    let z_con = gsem::gwas::gc_correction::gc_adjusted_z(
        &beta,
        &se,
        &i_ld,
        gsem::gwas::gc_correction::GcMode::Conservative,
        k,
    );
    let z_none = gsem::gwas::gc_correction::gc_adjusted_z(
        &beta,
        &se,
        &i_ld,
        gsem::gwas::gc_correction::GcMode::None,
        k,
    );

    let expected_std = json_to_vec(&fix["standard"]);
    let expected_con = json_to_vec(&fix["conservative"]);
    let expected_none = json_to_vec(&fix["none"]);

    assert_vec_close(&z_std, &expected_std, 1e-10, "Z_pre standard");
    assert_vec_close(&z_con, &expected_con, 1e-10, "Z_pre conservative");
    assert_vec_close(&z_none, &expected_none, 1e-10, "Z_pre none");
}

// ── Test Case 8: SEM fitting ────────────────────────────────────────────────

#[test]
fn test_sem_estimates_match_r() {
    let fix = load_fixture("sem_1factor");
    let s = json_to_mat(&fix["s"]);
    let v_diag = json_to_vec(&fix["v_diag"]);

    let r_estimates: Vec<(String, String, String, f64)> = fix["estimates"]
        .as_array()
        .unwrap()
        .iter()
        .map(|e| {
            (
                e["lhs"].as_str().unwrap().to_string(),
                e["op"].as_str().unwrap().to_string(),
                e["rhs"].as_str().unwrap().to_string(),
                e["est"].as_f64().unwrap(),
            )
        })
        .collect();

    // Parse and fit the same model
    let model_str = "F1 =~ NA*V1 + V2 + V3\nF1 ~~ 1*F1\nV1 ~~ V1\nV2 ~~ V2\nV3 ~~ V3";
    let pt = gsem_sem::syntax::parse_model(model_str, false).unwrap();
    let obs_names: Vec<String> = vec!["V1", "V2", "V3"]
        .into_iter()
        .map(String::from)
        .collect();
    let mut model = gsem_sem::model::Model::from_partable(&pt, &obs_names);

    let fit = gsem_sem::estimator::fit_dwls(&mut model, &s, &v_diag, 1000, None);
    assert!(fit.converged, "SEM should converge");

    // Compare ALL free parameter estimates (not just loadings)
    let free_rows: Vec<_> = pt.rows.iter().filter(|r| r.free > 0).collect();
    assert_eq!(
        free_rows.len(),
        fit.params.len(),
        "Number of free rows must match number of fitted params"
    );
    for (i, row) in free_rows.iter().enumerate() {
        let est = fit.params[i];
        if let Some(r_est) = r_estimates
            .iter()
            .find(|(l, o, r, _)| *l == row.lhs && *o == row.op.to_string() && *r == row.rhs)
        {
            let diff = (est - r_est.3).abs();
            assert!(
                diff < 0.05,
                "SEM param {} {} {}: Rust={est:.6} R={:.6} diff={diff:.6}",
                row.lhs, row.op, row.rhs, r_est.3
            );
        } else {
            panic!(
                "Free param {} {} {} not found in R reference estimates",
                row.lhs, row.op, row.rhs
            );
        }
    }

    // More robust check: the model-implied covariance should approximate S
    let implied = model.implied_cov();
    assert_mat_close(&implied, &s, 0.05, "SEM implied cov ≈ S");

    // Check objective is small (good fit)
    assert!(
        fit.objective < 0.1,
        "SEM objective should be small: {}",
        fit.objective
    );
}

// ── Test Case 8b: 2-factor SEM with fixed rows in middle of partable ────────
// This specifically tests that parameter indexing is correct when fixed rows
// (F1~~1*F1, F2~~1*F2) appear between free rows in the partable.

#[test]
fn test_sem_2factor_all_params_match_r() {
    let fix = load_fixture("sem_2factor");
    let s = json_to_mat(&fix["s"]);
    let v_diag = json_to_vec(&fix["v_diag"]);

    let r_estimates: Vec<(String, String, String, f64)> = fix["estimates"]
        .as_array()
        .unwrap()
        .iter()
        .map(|e| {
            (
                e["lhs"].as_str().unwrap().to_string(),
                e["op"].as_str().unwrap().to_string(),
                e["rhs"].as_str().unwrap().to_string(),
                e["est"].as_f64().unwrap(),
            )
        })
        .collect();

    let model_str = "F1 =~ NA*V1 + V2\nF2 =~ NA*V3 + V4\n\
                     F1 ~~ 1*F1\nF2 ~~ 1*F2\nF1 ~~ F2\n\
                     V1 ~~ V1\nV2 ~~ V2\nV3 ~~ V3\nV4 ~~ V4";
    let pt = gsem_sem::syntax::parse_model(model_str, false).unwrap();
    let obs_names: Vec<String> = vec!["V1", "V2", "V3", "V4"]
        .into_iter()
        .map(String::from)
        .collect();
    let mut model = gsem_sem::model::Model::from_partable(&pt, &obs_names);

    let fit = gsem_sem::estimator::fit_dwls(&mut model, &s, &v_diag, 1000, None);
    assert!(fit.converged, "2-factor SEM should converge");

    // Verify fixed rows exist in the partable (this is the key invariant)
    let n_fixed = pt.rows.iter().filter(|r| r.free == 0).count();
    assert!(
        n_fixed >= 2,
        "Partable should have at least 2 fixed rows (F1~~1*F1, F2~~1*F2), got {n_fixed}"
    );

    // Compare ALL free parameter estimates against R
    let free_rows: Vec<_> = pt.rows.iter().filter(|r| r.free > 0).collect();
    assert_eq!(
        free_rows.len(),
        fit.params.len(),
        "Number of free rows ({}) must match number of fitted params ({})",
        free_rows.len(),
        fit.params.len()
    );
    for (i, row) in free_rows.iter().enumerate() {
        let est = fit.params[i];
        if let Some(r_est) = r_estimates
            .iter()
            .find(|(l, o, r, _)| *l == row.lhs && *o == row.op.to_string() && *r == row.rhs)
        {
            let diff = (est - r_est.3).abs();
            assert!(
                diff < 0.05,
                "2-factor param {} {} {}: Rust={est:.6} R={:.6} diff={diff:.6}",
                row.lhs, row.op, row.rhs, r_est.3
            );
        } else {
            panic!(
                "Free param {} {} {} not found in R reference estimates",
                row.lhs, row.op, row.rhs
            );
        }
    }
}

// ── Test Case 9: V reorder ──────────────────────────────────────────────────

#[test]
fn test_v_reorder_matches_r() {
    let fix = load_fixture("reorder");
    let v = json_to_mat(&fix["v"]);
    let user_order: Vec<String> = fix["user_order"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_str().unwrap().to_string())
        .collect();
    let model_order: Vec<String> = fix["model_order"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_str().unwrap().to_string())
        .collect();
    let expected = json_to_mat(&fix["v_reordered"]);

    let result = gsem_sem::reorder::reorder_v(&v, &user_order, &model_order).unwrap();
    assert_mat_close(&result, &expected, 1e-12, "V reorder");
}

// ── Test Case 10: commonfactor (full pipeline with SEs) ─────────────────────

#[test]
fn test_commonfactor_matches_r() {
    let fix = load_fixture("commonfactor");
    let s = json_to_mat(&fix["s"]);
    let v = json_to_mat(&fix["v"]);

    let r_params: Vec<(String, String, String, f64)> = fix["parameters"]
        .as_array()
        .unwrap()
        .iter()
        .map(|e| {
            (
                e["lhs"].as_str().unwrap().to_string(),
                e["op"].as_str().unwrap().to_string(),
                e["rhs"].as_str().unwrap().to_string(),
                e["est"].as_f64().unwrap(),
            )
        })
        .collect();
    let r_sandwich_se = json_to_vec(&fix["sandwich_se"]);
    let r_implied = json_to_mat(&fix["implied_cov"]);

    let result =
        gsem_sem::commonfactor::run_commonfactor(&s, &v, gsem_sem::EstimationMethod::Dwls).unwrap();

    // Check parameter estimates match R
    assert_eq!(
        result.parameters.len(),
        r_params.len(),
        "parameter count mismatch"
    );
    for (rust_p, r_p) in result.parameters.iter().zip(r_params.iter()) {
        assert_eq!(rust_p.lhs, r_p.0, "lhs mismatch");
        assert_eq!(rust_p.rhs, r_p.2, "rhs mismatch");
        let diff = (rust_p.est - r_p.3).abs();
        assert!(
            diff < 0.02,
            "commonfactor param {}.{}.{}: Rust={:.6} R={:.6} diff={diff:.6}",
            rust_p.lhs,
            rust_p.op,
            rust_p.rhs,
            rust_p.est,
            r_p.3
        );
    }

    // Check sandwich SEs match R
    for (i, (rust_p, &r_se)) in result
        .parameters
        .iter()
        .zip(r_sandwich_se.iter())
        .enumerate()
    {
        let diff = (rust_p.se - r_se).abs();
        assert!(
            diff < 0.01,
            "commonfactor SE[{i}]: Rust={:.6} R={r_se:.6} diff={diff:.6}",
            rust_p.se
        );
    }

    // Check implied covariance matches R
    assert_mat_close(
        &result.implied_cov,
        &r_implied,
        1e-6,
        "commonfactor implied cov",
    );
}
