// Generated by extendr: Do not edit by hand
//
// This file was created with the following call:
//   .Call("wrap__make_gsemr_wrappers", use_symbols = TRUE, package_name = "gsemr")

#include <R.h>
#include <Rinternals.h>
#include <stdlib.h>
#include <R_ext/Rdynload.h>

/* .Call calls */
extern SEXP wrap__ldsc_rust(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
extern SEXP wrap__usermodel_rust(SEXP, SEXP, SEXP);
extern SEXP wrap__munge_rust(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"wrap__ldsc_rust",      (DL_FUNC) &wrap__ldsc_rust,      6},
    {"wrap__usermodel_rust", (DL_FUNC) &wrap__usermodel_rust, 3},
    {"wrap__munge_rust",     (DL_FUNC) &wrap__munge_rust,     6},
    {NULL, NULL, 0}
};

void R_init_gsemr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
