// Generated by extendr: Do not edit by hand

#include <R.h>
#include <Rinternals.h>
#include <stdlib.h>
#include <R_ext/Rdynload.h>

/* .Call calls */
extern SEXP wrap__ldsc_rust(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
extern SEXP wrap__usermodel_rust(SEXP, SEXP, SEXP);
extern SEXP wrap__munge_rust(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
extern SEXP wrap__commonfactor_rust(SEXP, SEXP);
extern SEXP wrap__sumstats_rust(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
extern SEXP wrap__commonfactor_gwas_rust(SEXP, SEXP, SEXP);
extern SEXP wrap__user_gwas_rust(SEXP, SEXP, SEXP, SEXP, SEXP);
extern SEXP wrap__pa_ldsc_rust(SEXP, SEXP);
extern SEXP wrap__write_model_rust(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
extern SEXP wrap__rgmodel_rust(SEXP, SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"wrap__ldsc_rust",              (DL_FUNC) &wrap__ldsc_rust,              6},
    {"wrap__usermodel_rust",         (DL_FUNC) &wrap__usermodel_rust,         3},
    {"wrap__munge_rust",             (DL_FUNC) &wrap__munge_rust,             6},
    {"wrap__commonfactor_rust",      (DL_FUNC) &wrap__commonfactor_rust,      2},
    {"wrap__sumstats_rust",          (DL_FUNC) &wrap__sumstats_rust,          7},
    {"wrap__commonfactor_gwas_rust", (DL_FUNC) &wrap__commonfactor_gwas_rust, 3},
    {"wrap__user_gwas_rust",         (DL_FUNC) &wrap__user_gwas_rust,         5},
    {"wrap__pa_ldsc_rust",           (DL_FUNC) &wrap__pa_ldsc_rust,           2},
    {"wrap__write_model_rust",       (DL_FUNC) &wrap__write_model_rust,       7},
    {"wrap__rgmodel_rust",           (DL_FUNC) &wrap__rgmodel_rust,           2},
    {NULL, NULL, 0}
};

void R_init_gsemr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
